coffe/coffe/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('order/<int:product_id>/', views.order, name = 'order'),
    path('or/', include('products.urls'), name = 'orders')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffe/products/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

app_name = 'orders'

urlpatterns = [
        path('order/<int:product_id>/', views.update_orders, name='update_orders'),
        path('order_list/',views.order_list, name = 'order_list'),
        path('keeper/', views.login_user , name = "login"),
        path('successfull/<int:order_id>/', views.succ, name = 'successfull')
]

coffe/products/models.py
from django.db import models



class products(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.CharField(max_length=10, default='$')
    description = models.CharField(max_length=255, default='')
    img2 = models.ImageField(default='fallback.png', blank=True)
    def __str__(self):
        return self.name
class orders(models.Model):
    product = models.ForeignKey('products', on_delete=models.CASCADE, default='001')
    F_name = models.CharField(max_length=50,null=False)
    M_name = models.CharField(max_length=50,null=False)
    phone = models.IntegerField(null=False)
    email = models.CharField(max_length=50, null=False)
    city = models.CharField( max_length=50)
    street = models.CharField( max_length=50)
    def __str__(self):
        return self.email

coffe/coffe/views.py
from django.shortcuts import render, redirect,get_object_or_404
from products.models import products, orders

def home(request):
    posts = products.objects.all()
    return render (request, 'layout.html',{'posts':posts})
def order(request, product_id):
    product = get_object_or_404(products, id=product_id)
    return render (request, 'orders.html',{'product':product})

coffe/products/views.py
from django.shortcuts import render, redirect,get_object_or_404
from products.models import products, orders
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
def succ(request, order_id):
    order = get_object_or_404(orders, id=order_id)
    template = render_to_string('products/email_template.html',
                                {'name':order.F_name,
                                'item':order.product
                                })
    email = EmailMessage(
        'Your Coffee Order is Confirmed!',
        template,
        settings.EMAIL_HOST_USER,
        [order.email]
    )
    email.send()
    return render(request, 'products/success.html',{'order': order})
def update_orders(request, product_id):
    if request.method == 'POST':
        print("Form submitted!")
        product = get_object_or_404(products, id=product_id)
        F_name = request.POST.get('name')
        M_name = request.POST.get('M_name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        city = request.POST.get('address') 
        street = request.POST.get('street')

        order = orders(
            product=product,
            F_name=F_name,
            M_name=M_name,
            phone=phone,
            email=email,
            city=city,
            street=street
        )
        order.save()

        return redirect('orders:successfull', order_id=order.id)
@login_required(login_url='orders:login')
def order_list(request):
    lists = orders.objects.all()
    return render(request, 'products/delivery.html', {'lists': lists})



def login_user(request):
    user_aut = False
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate (request=request, username = username, password=password)
        if user is not None:
            login(request, user)
            user_aut = True
            return redirect('orders:order_list')
        else:
            messages.error(request, '*Invalid username or password')
            return redirect('orders:login')
    return render(request, 'products/login.html')

coffe/products/templates/products/delivery.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shoppers page</title>
    <link rel="stylesheet" href="{% static 'css/cs.css' %}">
</head>
<body>
    <h1 class="main_heading">Orders right now</h1>
    <div class="orders">
        <table>
            <tr>
                <td>Email</td>
                <td>Name</td>
                <td>Product</td>
                <td>Phone</td>
                <td>Address</td>
            </tr>
            {% for list in lists%}
            <tr>
                <td>{{list.email}}</td>
                <td>{{list.F_name}} {{list.M_name}}</td>
                <td>{{list.product}}</td>
                <td>{{list.phone}}</td>
                <td>{{list.city}}, {{list.street}}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
</body>
</html>

coffe/products/templates/products/email_template.html
Hi {{name}},

Thanks for your order with Kaldis coffee!

We're happy to confirm that we've received your order:

Order Number:{{order_id}}
Order Details : {{item.description}}

{{item.name}}
{{item.img2}}

Total:{{item.price}}

If you have any questions or need to make changes, 
feel free to contact us at [Phone Number] or reply to this email.
We appreciate your business and look forward to fueling 
your day with great coffee!

Warm regards,
Kaldis Coffee
[Ethiopia,Addis ababa,Medhanialem] | kaldis.com 

coffe/products/templates/products/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login page</title>
    <link rel="stylesheet" href="{% static 'css/cs.css' %}">
</head>
<body>
    <form action="" method="POST">
    <h1 class="login_head">Login here if ur admin</h1>
    {% csrf_token %}
    {%if messages%}
            {% for message in messages%}
                {% if message.tags == 'error' %}
                    <h4 class="error">{{message}}</h4>
                {% else%}
                    <h4 class="success">{{message}}</h4>
                {%endif%}
            {% endfor%}
        {% endif%}
        <input type="text" placeholder="username" name="username">
        <input type="password" placeholder="password" name = "password">
        <input type="submit" placeholder="submit">
    </form>
</body>
</html>

coffe/products/templates/products/success.html
{%extends 'layout.html'%}
{%block content%}
<div class="succ_classes">
    <div class="succ_items">
    <h1 >Order successfuly placed😊</h1>
    <h2>We will call you soon</h2>
    <a href="{%url 'home'%}">Return &rarr;</a>
    </div>
</div>
{% endblock %}

coffe/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>coffee_shop</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanalei&family=Poiret+One&display=swap" rel="stylesheet">
</head>
<body>
    <!--navbar section-->
    <section class="nav">
    <span>Kaldis </span>
        <nav class="navbar">
            <ul class="navbar_elements">
                <li class="navbar_items"><a href="#home" class="navbar_links">Home</a></li>
                <li class="navbar_items"><a href="#product" class="navbar_links">Products</a></li>
                <li class="navbar_items"><a href="#about" class="navbar_links">About</a></li>
                <li class="navbar_items"><a href="#contact" class="navbar_links">Contact</a></li>
            </ul>
        </nav>
    </section>
    <!--end of navbar section-->
    {%block content%}
    <!--home section-->
    <section id="home">
        <div class="home_text_">
            <p>Helloo!</p>
            <h1>Start your day with a little <br>cup of comfort</h1>
            <button><a href="#product">Products</a></button>
        </div>
        <img src="{%static 'image/coff.jpg'%}" height="850" width="750">
    </section>
    <!--end of home section-->
    <!--product section-->
    <section id="product">
        <h1>Products</h1>
        <div class="product_cont">
            {%for post in posts%}
                <div class="product_items">
                    <img src="{{post.img2.url}}" alt="" height="200" width="400">
                    <h2>{{post.name}}</h2>
                    <h3>{{post.price}}</h3>
                    <div class="text_holder"> 
                    <p>{{post.description}}</p><button><a href="{%url 'order' post.id%}">Place order</a></button>    
                    </div>
                    
                </div>
            {%endfor%}
        </div>
    {%endblock%}
    
    </section>
    <!-- end of product section-->
     <!--about section-->
     <section id="about">
        <div class="about_logo">
            <img src="{%static 'image/about.jpg'%}" alt="Coffee image" >
            <div class="about_para">
                <h1>About</h1>
                <h2><span>70%</span>off your first cup at Kaldi's 
                    Coffee – where every sip tells a story. Inspired by
                    the legendary goat herder Kaldi, who discovered
                    coffee's energizing power, our shop blends
                    tradition with modern comfort. Whether you're 
                    a devoted espresso lover or just looking for 
                    a cozy spot to unwind, Kaldi's Coffee serves
                    handpicked, ethically sourced beans brewed to
                    perfection. From smooth lattes to bold 
                    pour-overs, we craft each drink with care 
                    in a welcoming atmosphere made for connection
                    and calm. Come in for the coffee, stay for 
                    the community.</h2>
            </div>
        </div>
     </section>
    <!-- end of about section-->
     <!--contact section-->
     <section id="contact">
        <div class="cont_layer1">
            <div class="cont_icons">
                <h1>Kaldis</h1>
            </div>
            <div class="social_media">
                <p>You can get us 24/7 with those social<br> media accounts at any time you want</p>
                <a href=""><i class="fa-brands fa-facebook-f"></i></a>
                <a href=""><i class="fa-brands fa-telegram"></i></a></i>
                <a href=""><i class="fa-brands fa-twitter"></i></a></i>
            </div>
        </div>
        <div class="footer_nav">
            <h2>About</h2>
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#product">product</a>
        </div>
        <div class="get_in">
            <h2>Get in touch</h2>
            <p><i class="fa-solid fa-location-dot"></i>Addis ababa, Ethiopia</p>
            <p><i class="fa-solid fa-phone"></i>+251-992-013-392</p>
            <p><i class="fa-brands fa-telegram"></i>+251-977-629-578</p>
            <p><i class="fa-solid fa-envelope"></i>KaldisCoffee@gmail.com</p>
        </div>
     </section>
    <!-- end of contact section-->

<script src="https://kit.fontawesome.com/b50902bacd.js" crossorigin="anonymous"></script>
<script src="{% static 'js/js.js'%}"></script>
</body>
</html>

coffe/templates/orders.html
{% extends "layout.html" %}
{%block content%}
<div class="order">
<div class="order_content">
    <div class="selected_product">
        <img src="{{product.img2.url}}" alt="" height = "150">
        <h2>{{product.name}}</h2>
        <h3>{{product.price}}</h3>
        <p>{{product.description}}</p>
    </div>
    <div class="personal_info">
        <form method="POST" action="{% url 'orders:update_orders' product.id %}" class="personal_info_form">
            {% csrf_token %}
            <h1>Enter you information</h1>
            <div class="full_name">
                <label for="name">Full Name</label>
                <input type="text" placeholder="First name" name="name">
                <input type="text" placeholder="last name" name="M_name">
            </div>
            <div class="phone_number">
            <label for="phone">Phone number</label>
            <input type="phone2numeric" placeholder="+251-9XX-XXX-XXX" name =  'phone'>
            </div>
            <div class="email">
            <label for="email">Email</label>
            <input type="email" placeholder="Email" name= 'email'>
            </div>
            <div class="ship_add">
            <label for="addres">Addres</label>
            <input type="text" placeholder="City" name= 'address'>
            <input type="text" placeholder="street" name = 'street'>
            </div>
            <input type="submit" value="Order" class="order_button">
            <input type="hidden" name="product_id" value="{{ product.id }}">
        </form>
    </div>
</div>
</div>
{% endblock %}